skip-check:
  # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty
  - CKV_GHA_7
  # Ensure that HTTPS url is used with uri
  - CKV2_ANSIBLE_1
  # Ensure that HTTPS url is used with get_url
  - CKV2_ANSIBLE_2
